#! /usr/bin/env python
import os
import sys
import glob

def finder():
   for item in sys.path:
        for root, dirs, files in os.walk(item):
            for victim in glob.glob(os.path.join(root, '*.py')):
                yield victim

if __name__ == '__main__':
   print(list(finder()))

